### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ggt** [opensearch-project/alerting#1526]
**Environement**
Docker

**What is the bug?**
Triggers & Alerts created in schema version 0 and produces java.lang.NullPointerException: null.

**How can one reproduce the bug?**

- Create an alert and trigger on an old opensearch version
- Update it to 2.13.0

**What is the expected behavior?**
sudo docker-compose logs opensearch -f --tail 100

**Do you have any screenshots?**
`opensearch-node1                | [2024-04-23T10:58:21,094][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [P00APLOG-D01] uncaught exception in thread [DefaultDispatcher-worker-4]
opensearch-node1                | java.lang.NullPointerException: null
opensearch-node1                | 	at org.opensearch.alerting.MonitorRunnerService$runJob$2.invokeSuspend(MonitorRunnerService.kt:335) ~[opensearch-alerting-2.13.0.0.jar:2.13.0.0]
opensearch-node1                | 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.8.21.jar:1.8.21-release-380(1.8.21)]
opensearch-node1                | 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
opensearch-node1                | 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
opensearch-node1                | 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
opensearch-node1                | 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
opensearch-node1                | uncaught exception in thread [DefaultDispatcher-worker-4]`

**Differences**
```
<     "schema_version": 0,
>     "schema_version": 8,

<       "source": "Alerting Notification action",
>       "source": "",      //   Suspecting that to be the issue!
```

**Temporary solution**
Copy informations from old and create a new alert and trigger
[new.txt](https://github.com/opensearch-project/alerting/files/15079000/new.txt)
[old.txt](https://github.com/opensearch-project/alerting/files/15079001/old.txt)

**TODO**
Check in the code if "source" is Null produces that error, (no more infos in debug)

Thanks!

**Comment by sbcd90** [comment]
looking into it. added to backlog.

**Comment by zakisaad** [comment]
Can confirm this occurred to 5 of our monitors on AWS hosted OS - the frustrating part about this is the complete silence/"green status" on the OpenSearch dashboards, which makes it look like everything is firing per usual. Only tell is the NPE log thrown every time the monitor was supposed to run.

**Comment by diegargon** [comment]
I got similar problem.

[2024-06-18T08:45:45,552][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch] uncaught exception in thread [DefaultDispatcher-worker-8]
java.lang.NullPointerException: null
        at org.opensearch.alerting.MonitorRunnerService$runJob$1.invokeSuspend(MonitorRunnerService.kt:345) ~[opensearch-alerting-2.14.0.0.jar:2.14.0.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.8.21.jar:1.8.21-release-380(1.8.21)]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]


I got this problem a month ago, i fixit (i try few things but not remember) after a reboot yesterday the error appeared again.

**Comment by zakisaad** [comment]
We had to export -> import all of our monitors using the JSON Export feature, as we had used the UI to define the monitors directly. The 2.13 upgrade has been painful for us.

I suggest you export each of the monitors in JSON form, disable them, go to the Dev Tools console in the sidebar, and re-import each of them using a POST request (you might want to strip the `id` fields from the exported JSON).

If you define monitors using IaC (Terraform or some other in-house tooling), deleting the monitors and re-creating them via your pipelines should also work as a simple solution.

**Comment by diegargon** [comment]
Yes, that's what I think I remember doing the first time it happened but manually, but this time it didn't work.

**Comment by ggt** [comment]
If they don t appears, search for my other thread to fix it! I shown how to
modify the request to be able to see them

**Comment by jowg-amazon** [comment]
Hi, the null pointer exception is a bug in 2.13 coming from a log statement here: https://github.com/opensearch-project/alerting/blob/8007d0a43d8077af4c9b3cedc91c747a75b683e6/alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt#L338

It has been fixed in this PR: https://github.com/opensearch-project/alerting/pull/1630/files. Until the code fix is released here are the steps you can perform for a temporary solution.

```
// Check if there are any stuck locks
POST .opensearch-alerting-config-lock/_search?pretty
{
  "query": {
    "match": {
      "released": "false"
    }
  }
}

// Delete all stuck locks
POST .opensearch-alerting-config-lock/_delete_by_query?pretty
{
  "query": {
    "match": {
      "released": "false"
    }
  }
}
```

**Comment by ilyaevseev** [comment]
The same problem with OpenSearch 2.15.0 on one of our cluster nodes:
```
[2024-12-31T10:48:41,629][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [es4.internal] uncaught exception in thread [DefaultDispatcher-worker-36]
java.lang.NullPointerException: null
        at org.opensearch.alerting.MonitorRunnerService$runJob$2.invokeSuspend(MonitorRunnerService.kt:377) ~[opensearch-alerting-2.15.0.0.jar:2.15.0.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.8.21.jar:1.8.21-release-380(1.8.21)]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
```
