### ISSUE TITLE
[Feature] Add support for Cross-cluster search 

### ISSUE THREAD

**Issue by Crazyigor1987** [opensearch-project/alerting#207]
There is an open issue from open-distro, which has now also migrated to the new opensearch project.
[alerting-kibana-plugin/issues/154](https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/154)

Following this [issue](https://github.com/opendistro-for-elasticsearch/alerting/issues/62) seems like CCS is supported when creating monitors directly from the API but not from the UI.
The reason is probably that Opensearch doesn't expose the mapping for remote indices via CCS.

**Comment by CEHENKLE** [comment]
Hey folks, have you been able to repo this in OpenSearch? 

Thanks,
/C

**Comment by aditjind** [comment]
Hey Charlotte! I am on PTO. Will get someone to look first thing after a couple of weeks. If urgent, please reach out to my manager @praveensameneni for further details.

**Comment by lezzago** [comment]
This feature has not been officially supported, but this will be looked into to see when we can improve this experience on the UI and officially support the CCS feature.

**Comment by williamhargrove** [comment]
Is there any update on this issue through the UI? I have successfully created an index pattern that can be used through 'Discover' to query a remote set of clusters. When I try and add this pattern to Alerting and run a query against it, I get permission issues related to the `plugin` user (which I see doesn't seem to exist as an internal users.

Versions: opendistro elasticsearch: 1.13.3 and opendistro kibana: 1.13.2 - but looking to migrate to OpenSearch shortly.

Error from the calling cluster:

```Caused by: org.elasticsearch.ElasticsearchSecurityException: no permissions for [indices:data/read/search] and User [name=plugin, backend_roles=[], requestedTenant=null]```

Error on the remote cluster:

```[2022-05-31T10:50:54,422][INFO ][c.a.o.s.p.PrivilegesEvaluator] [remote-cluster] No index-level perm match for User [name=plugin, backend_roles=[], requestedTenant=null] Resolved [aliases=[], allIndices=[filebeat-2022.05.28, filebeat-2022.05.26, filebeat-2022.05.29, filebeat-2022.05.27, filebeat-2022.05.31, filebeat-2022.05.30, filebeat-2022.05.25], types=[*], originalRequested=[filebeat-*], remoteIndices=[]] [Action [indices:data/read/search]] [RolesChecked [own_index]]```


```[2022-05-31T10:50:54,422][INFO ][c.a.o.s.p.PrivilegesEvaluator] [remote-cluster] No permissions for [indices:data/read/search]```

**Comment by williamhargrove** [comment]
@lezzago and @Crazyigor1987 - Nudge on this. Is it possible to raise this issue as it is having an impact on our rollout of OpenSearch. Thanks.

**Comment by tastyfrankfurt** [comment]
Hey Guys, I managed to work around the perms issue by creating the following role and role mapping on the child cluster
####Role Mapping
asynchronous_search_full_access:
  reserved: false
  description: "Allow monitors to search userdata from osp cluster."
  users:
  - "plugin"

####Role
asynchronous_search_full_access:
  reserved: true
  cluster_permissions:
    - 'cluster:admin/opendistro/asynchronous_search/*'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'indices:data/read/search*'

This resolve issues in the GUI on the parent cluster but now i get another issue where the connection gets dropped from the remote cluster when an alert is configured to run on the parent cluster.
[2022-07-20T06:35:57,776][WARN ][o.o.t.SniffConnectionStrategy] [parentsvr03.example.local] fetching nodes from external cluster [childclustername] failed
org.opensearch.transport.ConnectTransportException: [][10.0.0.3:9300] connect_timeout[30s]
        at org.opensearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:1070) ~[opensearch-1.3.1.jar:1.3.1]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733) ~[opensearch-1.3.1.jar:1.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[2022-07-20T06:35:57,778][INFO ][o.o.a.InputService       ] [parentsvr03.example.local] Error collecting inputs for monitor: B7rvGIIBydydB7i6UFHM
org.opensearch.transport.RemoteTransportException: [error while communicating with remote cluster [childclustername]]
Caused by: org.opensearch.transport.ConnectTransportException: [][10.0.0.3:9300] connect_timeout[30s]
        at org.opensearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:1070) ~[opensearch-1.3.1.jar:1.3.1]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733) ~[opensearch-1.3.1.jar:1.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-07-20T06:35:57,778][INFO ][o.o.a.InputService       ] [parentsvr03.example.local] Error collecting inputs for monitor: B7rvGIIBydydB7i6UFHM
org.opensearch.transport.RemoteTransportException: [error while communicating with remote cluster [childclustername]]
Caused by: org.opensearch.transport.ConnectTransportException: [][10.0.0.3:9300] connect_timeout[30s]
        at org.opensearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:1070) ~[opensearch-1.3.1.jar:1.3.1]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733) ~[opensearch-1.3.1.jar:1.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
[2022-07-20T06:35:57,779][INFO ][o.o.a.TriggerService     ] [parentsvr03.example.local] Error running script for monitor B7rvGIIBydydB7i6UFHM, trigger: W_ZIGo                                                             IB56jjufonoo7W
org.opensearch.script.ScriptException: runtime error
        at org.opensearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:109) ~[lang-painless-1.3.1.jar:1.3.1]
        at org.opensearch.painless.PainlessScript$Script.execute(ctx.results[0].hits.total.value > 0:1) ~[?:?]
        at org.opensearch.alerting.TriggerService.runQueryLevelTrigger(TriggerService.kt:47) [opensearch-alerting-1.3.1.0.jar:1.3.1.0]
        at org.opensearch.alerting.MonitorRunner.runQueryLevelMonitor(MonitorRunner.kt:289) [opensearch-alerting-1.3.1.0.jar:1.3.1.0]
        at org.opensearch.alerting.MonitorRunner$runQueryLevelMonitor$1.invokeSuspend(MonitorRunner.kt) [opensearch-alerting-1.3.1.0.jar:1.3.1.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)                                                             ]
        at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:46) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:28) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:264) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:762) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)                                                             ]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:285) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
        at kotlin.collections.EmptyList.get(Collections.kt:35) ~[?:?]
        at kotlin.collections.EmptyList.get(Collections.kt:23) ~[?:?]
        at org.opensearch.painless.PainlessScript$Script.execute(ctx.results[0].hits.total.value > 0:12) ~[?:?]
        ... 16 more
[2022-07-20T06:35:57,780][INFO ][o.o.a.TriggerService     ] [parentsvr03.example.local] Error running script for monitor B7rvGIIBydydB7i6UFHM, trigger: W_ZIGo                                                             IB56jjufonoo7W
org.opensearch.script.ScriptException: runtime error
        at org.opensearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:109) ~[lang-painless-1.3.1.jar:1.3.1]
        at org.opensearch.painless.PainlessScript$Script.execute(ctx.results[0].hits.total.value > 0:1) ~[?:?]
        at org.opensearch.alerting.TriggerService.runQueryLevelTrigger(TriggerService.kt:47) [opensearch-alerting-1.3.1.0.jar:1.3.1.0]
        at org.opensearch.alerting.MonitorRunner.runQueryLevelMonitor(MonitorRunner.kt:289) [opensearch-alerting-1.3.1.0.jar:1.3.1.0]
        at org.opensearch.alerting.MonitorRunner$runQueryLevelMonitor$1.invokeSuspend(MonitorRunner.kt) [opensearch-alerting-1.3.1.0.jar:1.3.1.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)                                                             ]
        at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:46) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:28) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:264) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:762) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)                                                             ]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:285) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
        at kotlin.collections.EmptyList.get(Collections.kt:35) ~[?:?]
        at kotlin.collections.EmptyList.get(Collections.kt:23) ~[?:?]
        at org.opensearch.painless.PainlessScript$Script.execute(ctx.results[0].hits.total.value > 0:12) ~[?:?]
        ... 16 more
