### ISSUE TITLE
Add support for multi-bucket aggregation in "Per bucket monitor"

### ISSUE THREAD

**Issue by davidshtian** [opensearch-project/alerting#254]
**Is your feature request related to a problem? Please describe.**
From the description of the docs [here](https://opensearch.org/docs/latest/monitoring-plugins/alerting/monitors/#create-triggers), it seems that only **_composite aggregation_** query is supported in **_Per bucket monitor_**, while sometime users might need [multi-bucket](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-multi-terms-aggregation.html#search-aggregations-bucket-multi-terms-aggregation) aggregation to implement features like sorting or parameters like min_doc_count, etc. 

And then compare the values for each bucket, it might be similar to the Elasticsearch [watch array compare condition](https://www.elastic.co/guide/en/elasticsearch/reference/current/condition-array-compare.html) feature.

**Describe the solution you'd like**
To support multi-bucket aggregation in monitor triggers extraction query.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by davidshtian** [comment]
Besides, there're very few description and examples within docs for alerting monitor and trigger, and it might be hard for OpenSearch users to debug and troubleshooting of configurations. Thanks~

**Comment by rishabhmaurya** [comment]
Multi-bucket aggregation is supported in bucket monitors. I can see you are referring to multi-term aggregation in the question, assuming that's what you meant, then you're right as we don't support `multi_terms` aggregation yet in opensearch. It is part of xpack analytics plugins in elasticsearch and opensearch don't have anything similar yet.
Also, its not just composite aggregation, but all bucket, metric aggregations [here](https://github.com/opensearch-project/OpenSearch/tree/main/server/src/main/java/org/opensearch/search/aggregations) are supported with bucket selector.

I agree that documentation needs better examples, but while we fix it, below are some of the examples related to selecting a bucket from search results in bucket monitors, which people might find useful - 

```
curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'                                                                                                                      ~
{
   "size": 0,
   "aggs": {
      "sports_agg_multi": {
         "terms": {"field": "sport"},
         "aggs": {
            "goals_stats": { "stats": { "field": "goals" } }
         }
      },
      "trigger_bucket_selector1": {
         "bucket_selector_ext": {
            "buckets_path": {
              "avg": "goals_stats.avg"
            },
            "script": {
              "source": "params.avg >= 1.1 "
            },
            "parent_bucket_path": "sports_agg_multi",
            "filter": {
               "include": ["Football", "Handball"]
            }
         }
      },
      "trigger_bucket_selector2": {
         "bucket_selector_ext": {
            "buckets_path": {
              "avg": "goals_stats.avg"
            },
            "script": {
              "source": "params.avg >= 2"
            },
            "parent_bucket_path": "sports_agg_multi",
            "filter": {
               "include": ".*ball"
            }
         }
      },
      "trigger_bucket_selector3": {
        "bucket_selector_ext": {
            "buckets_path": {
              "avg": "goals_stats.avg"
            },
            "script": {
              "source": "params.avg >= 5"
            },
            "parent_bucket_path": "sports_agg_multi"
         }
      }
   }
}'
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 20,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "sports_agg_multi" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "Football",
          "doc_count" : 8,
          "goals_stats" : {
            "count" : 8,
            "min" : 34.0,
            "max" : 84.0,
            "avg" : 55.125,
            "sum" : 441.0
          }
        },
        {
          "key" : "Basketball",
          "doc_count" : 5,
          "goals_stats" : {
            "count" : 5,
            "min" : 848.0,
            "max" : 1483.0,
            "avg" : 1177.0,
            "sum" : 5885.0
          }
        },
        {
          "key" : "Hockey",
          "doc_count" : 4,
          "goals_stats" : {
            "count" : 4,
            "min" : 113.0,
            "max" : 218.0,
            "avg" : 150.75,
            "sum" : 603.0
          }
        },
        {
          "key" : "Handball",
          "doc_count" : 3,
          "goals_stats" : {
            "count" : 3,
            "min" : 143.0,
            "max" : 443.0,
            "avg" : 245.33333333333334,
            "sum" : 736.0
          }
        }
      ]
    },
    "trigger_bucket_selector1" : {
      "parent_bucket_path" : "sports_agg_multi",
      "bucket_indices" : [
        0,
        3
      ]
    },
    "trigger_bucket_selector2" : {
      "parent_bucket_path" : "sports_agg_multi",
      "bucket_indices" : [
        0,
        1,
        3
      ]
    },
    "trigger_bucket_selector3" : {
      "parent_bucket_path" : "sports_agg_multi",
      "bucket_indices" : [
        0,
        1,
        2,
        3
      ]
    }
  }
}'
```
in this example `trigger_bucket_selector1` will select ["Football", "Handball"] sport buckets if average goals >= 1.1
whereas `trigger_bucket_selector2`  will select sports ending with ball if average goals >= 2
`trigger_bucket_selector3` doesn't have any key filters, so it includes all sports where average goals >= 2.
You're free to use any bucket aggregation [here](https://github.com/opensearch-project/OpenSearch/tree/main/server/src/main/java/org/opensearch/search/aggregations/bucket) which includes composite aggregation, and you can use key `filter` with `include exclude`  as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_4)
More details can be found [here](https://github.com/opensearch-project/alerting/pull/144)

**Comment by rishabhmaurya** [comment]
can you elaborate your use-case or an example query would be helpful. Most of the use-cases of multi-term aggregation can be solved using composite aggregations if its doesn't involve sorting the results.

**Comment by davidshtian** [comment]
> can you elaborate your use-case or an example query would be helpful. Most of the use-cases of multi-term aggregation can be solved using composite aggregations if its doesn't involve sorting the results.

Really appreciate for your help~ Following the examples, I've tried multi-bucket aggregation and it works, the issue before might be related of not using the correct format or parameter. Kindly looking forward to see more use cases examples added to OpenSearch docs soon, thanks~

**Comment by davidshtian** [comment]
> can you elaborate your use-case or an example query would be helpful. Most of the use-cases of multi-term aggregation can be solved using composite aggregations if its doesn't involve sorting the results.

Hi~ I've tried the multi-bucket aggregation and it can be configured successfully, while after I set the alerting trigger it seems that the multi-bucket aggregation cannot trigger, but with equivalent composite query it works well. Not sure if there is any configuration difference for these queries.

I've also tested 2 other scenarios:
1) first using composite query and the trigger worked, then I modified to multi-bucket query, it could continue be triggered;
2) first using multi-bucket query and the trigger did not worked, then I modified to composite query, it could be triggered;

The queries are very simple, as shown below:
```
GET my-index-nginx-log/_search
{
  "size": 0,
  "aggregations": {
    "my_bucket": {
      "terms": {
        "field": "url.keyword"
      }
    }
  }
}

GET my-index-nginx-log/_search
{
  "size": 0,
  "aggs": {
    "my_bucket": {
      "composite": {
        "sources": [
          {
            "bucket": {
              "terms": {
                "field": "url.keyword"
              }
            }
          }
        ]
      }
    }
  }
}
```

And both trigger are set as below:
```
{
    "buckets_path": {
        "count_var": "_count"
    },
    "parent_bucket_path": "my_bucket",
    "script": {
        "source": "params.count_var > 2",
        "lang": "painless"
    },
    "gap_policy": "skip"
}
```

**Comment by davidshtian** [comment]
For the question above, if I execute the query below:
```
GET /_search?pretty
{
  "size": 0,
  "aggregations": {
    "my_bucket": {
      "terms": {
        "field": "url.keyword"
      },
      "aggs": {
        "avg_res": {
          "avg": {
            "field": "response_time"
          }
        }
      }
    },
    "trigger_bucket_selector1": {
      "bucket_selector_ext": {
        "buckets_path": {
          "_count": "_count"
        },
        "script": {
          "source": "params._count > 2 "
        },
        "parent_bucket_path": "my_bucket"
      }
    }
  }
}
```

The result would be:
```
{
  "took" : 8,
  "timed_out" : false,
  "_shards" : {
    "total" : 26,
    "successful" : 26,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 27,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "my_bucket" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "www.qq.com",
          "doc_count" : 3,
          "avg_res" : {
            "value" : 2.0
          }
        },
        {
          "key" : "www.baidu.com",
          "doc_count" : 2,
          "avg_res" : {
            "value" : 1.5
          }
        }
      ]
    },
    "trigger_bucket_selector1" : {
      "parent_bucket_path" : "my_bucket",
      "bucket_indices" : [
        0
      ]
    }
  }
}
```

And it seems that the result can also indicate there are alerts need to be triggered, so I'm asking for help about how to configure the single-bucket and multi-bucket alerting trigger configuration? Thanks a lot~

**Comment by davidshtian** [comment]
Previously, I'm using AOS managed service with OpenSearch 1.1 environment. And later I tested using self-build OpenSearch 1.2.0 on EC2, the result was the opposite... 

The single-bucket and multi-bucket aggregation can trigger alerting successfully, but composite aggregation cannot trigger.

**Comment by davidshtian** [comment]
I use alerting API to retrieve the monitor information, they're almost the same expect the user part of self-build env. And also not sure if the error logs from self-build env could help, thanks~
OpenSearch 1.2 on EC2:
```
[2022-02-15T14:09:00,091][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [e27e2ae74f2e] uncaught exception in thread [DefaultDispatcher-worker-3]
java.lang.UnsupportedOperationException: null
	at java.util.Collections$1.remove(Collections.java:4787) ~[?:?]
	at java.util.AbstractMap.remove(AbstractMap.java:254) ~[?:?]
	at org.opensearch.alerting.AlertService.getCategorizedAlertsForBucketLevelMonitor(AlertService.kt:238) ~[opensearch-alerting-1.2.0.0.jar:1.2.0.0]
	at org.opensearch.alerting.MonitorRunner.runBucketLevelMonitor(MonitorRunner.kt:421) ~[opensearch-alerting-1.2.0.0.jar:1.2.0.0]
	at org.opensearch.alerting.MonitorRunner$runBucketLevelMonitor$1.invokeSuspend(MonitorRunner.kt) ~[opensearch-alerting-1.2.0.0.jar:1.2.0.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$1.remove(Collections.java:4787)
	at java.base/java.util.AbstractMap.remove(AbstractMap.java:254)
	at org.opensearch.alerting.AlertService.getCategorizedAlertsForBucketLevelMonitor(AlertService.kt:238)
	at org.opensearch.alerting.MonitorRunner.runBucketLevelMonitor(MonitorRunner.kt:421)
	at org.opensearch.alerting.MonitorRunner$runBucketLevelMonitor$1.invokeSuspend(MonitorRunner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```
OpenSearch 1.1 on EC2:
```
uncaught exception in thread [DefaultDispatcher-worker-4]
java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$1.remove(Collections.java:4787)
	at java.base/java.util.AbstractMap.remove(AbstractMap.java:254)
	at org.opensearch.alerting.AlertService.getCategorizedAlertsForBucketLevelMonitor(AlertService.kt:239)
	at org.opensearch.alerting.MonitorRunner.runBucketLevelMonitor(MonitorRunner.kt:421)
	at org.opensearch.alerting.MonitorRunner$runBucketLevelMonitor$1.invokeSuspend(MonitorRunner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
[2022-02-15T14:06:00,403][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [b2f4649f4b27] uncaught exception in thread [DefaultDispatcher-worker-4]
java.lang.UnsupportedOperationException: null
	at java.util.Collections$1.remove(Collections.java:4787) ~[?:?]
	at java.util.AbstractMap.remove(AbstractMap.java:254) ~[?:?]
	at org.opensearch.alerting.AlertService.getCategorizedAlertsForBucketLevelMonitor(AlertService.kt:239) ~[opensearch-alerting-1.1.0.0.jar:1.1.0.0]
	at org.opensearch.alerting.MonitorRunner.runBucketLevelMonitor(MonitorRunner.kt:421) ~[opensearch-alerting-1.1.0.0.jar:1.1.0.0]
	at org.opensearch.alerting.MonitorRunner$runBucketLevelMonitor$1.invokeSuspend(MonitorRunner.kt) ~[opensearch-alerting-1.1.0.0.jar:1.1.0.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
```

**Comment by davidshtian** [comment]
@rishabhmaurya  I could use below codes to reproduce the issue, for your references. Thanks~
```
# DELETE my-index-nginx-log

PUT my-index-nginx-log

POST my-index-nginx-log/_bulk
{"index":{}}
{"url":"www.qq.com","response_time":1}
{"index":{}}
{"url":"www.qq.com","response_time":2}
{"index":{}}
{"url":"www.baidu.com","response_time":3}
{"index":{}}
{"url":"www.baidu.com","response_time":5}
{"index":{}}
{"url":"www.baidu.com","response_time":10}
{"index":{}}
{"url":"www.baidu.com","response_time":11}
{"index":{}}
{"url":"www.baidu.com","response_time":8}
{"index":{}}
{"url":"www.baidu.com","response_time":4}
{"index":{}}
{"url":"www.baidu.com","response_time":9}

POST _plugins/_alerting/monitors
{
  "type": "monitor",
  "name": "bucket",
  "monitor_type": "bucket_level_monitor",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "search": {
        "indices": [
          "my-index-nginx-log"
        ],
        "query": {
          "size": 0,
          "aggregations": {
            "my_bucket": {
              "terms": {
                "field": "url.keyword"
              },
              "aggs": {
                "avg_res": {
                  "avg": {
                    "field": "response_time"
                  }
                }
              }
            }
          }
        }
      }
    }
  ],
  "triggers": [
    {
      "bucket_level_trigger": {
        "name": "buck-trigger",
        "severity": "1",
        "condition": {
          "buckets_path": {
            "_count": "_count"
          },
          "script": {
            "source": "params._count > 2 "
          },
          "parent_bucket_path": "my_bucket"
        },
        "actions": []
      }
    }
  ]
}

POST _plugins/_alerting/monitors
{
  "type": "monitor",
  "name": "com",
  "monitor_type": "bucket_level_monitor",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "search": {
        "indices": [
          "my-index-nginx-log"
        ],
        "query": {
          "size": 0,
          "aggs": {
            "my_bucket": {
              "composite": {
                "sources": [
                  {
                    "bucket": {
                      "terms": {
                        "field": "url.keyword"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  ],
  "triggers": [
    {
      "bucket_level_trigger": {
        "name": "com-trigger",
        "severity": "1",
        "condition": {
          "buckets_path": {
            "_count": "_count"
          },
          "script": {
            "source": "params._count > 2 "
          },
          "parent_bucket_path": "my_bucket"
        },
        "actions": []
      }
    }
  ]
}
```

In addition, I could use these queries to create monitor successfully, while when I switch to alerting page on Kibana, the page showed blank with errors in console below:
```
TypeError: groupBy is undefined
    insertGroupByColumn http://172.31.29.59:5601/36526/bundles/plugin/alertingDashboards/alertingDashboards.chunk.2.js:1
    render http://172.31.29.59:5601/36526/bundles/plugin/alertingDashboards/alertingDashboards.chunk.2.js:1
```

And I edit the query but without any changes just click again and save, then I refresh the page the 'modified' monitor can be seen normally, but the 'not modified' monitor still cannot be seen normally. 

Thanks~

**Comment by davidshtian** [comment]
Previously, I use single node on EC2 and multiple data nodes on AOS, and I complement the test and summarize the test results below, for your reference. 

| Type | AOS 2 nodes (1.1) | AOS 1 node (1.1)| EC2 2 nodes (1.1 & 1.2) | EC2 1 node (1.1 & 1.2)  |
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| Composite Aggregation | yes | no  | yes |  no | 
| Bucket Aggregation  | no  | yes  | no | yes  | 

*Notes: Node for multiple nodes means data node, Bucket Aggregation means normal single or multi bucket aggregation.

It looks like that Composite Aggregation works well for cluster mode, and Bucket Aggregation works well for single node mode, not sure if this could help. Thanks~

**Comment by davidshtian** [comment]
It's more and more confusing... The clusters above including AOS and EC2 are old clusters, and composite agg can be used, while newly created AOS cluster (1 or more nodes) can only use single or multi bucket agg...

**Comment by davidshtian** [comment]
Did another round of test... It is not relevant of cluster or self-build, but it looks like that term agg and composite has some conflicts, and it will always trigger the first triggered one.

1. First create composite agg first, it throws errors below:

```
[2022-02-16T14:16:27,138][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [4b108816c25a] uncaught exception in thread [DefaultDispatcher-worker-1]
java.lang.UnsupportedOperationException: null
	at java.util.Collections$1.remove(Collections.java:4787) ~[?:?]
	at java.util.AbstractMap.remove(AbstractMap.java:254) ~[?:?]
	at org.opensearch.alerting.AlertService.getCategorizedAlertsForBucketLevelMonitor(AlertService.kt:238) ~[opensearch-alerting-1.2.4.0.jar:1.2.4.0]
	at org.opensearch.alerting.MonitorRunner.runBucketLevelMonitor(MonitorRunner.kt:421) ~[opensearch-alerting-1.2.4.0.jar:1.2.4.0]
	at org.opensearch.alerting.MonitorRunner$runBucketLevelMonitor$1.invokeSuspend(MonitorRunner.kt) ~[opensearch-alerting-1.2.4.0.jar:1.2.4.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
```
2. And then I create term agg, it cannot be triggered
3. And then I create composite agg, it cannot be triggered
4. The error messages above still keep throwing

And the opposite action order:
1. First create term agg first, it can be triggered
2. And then I create composite agg, it cannot be triggered
3. And then I create term agg, it can be triggered
4. The error messages above do not occur

Thanks~
