### ISSUE TITLE
SMTP email sender without SSL/TLS AUTH fails with javax.mail.MessagingException: Invalid Addresses

### ISSUE THREAD

**Issue by pantovad** [opensearch-project/alerting#461]
**What is the bug?**
SMTP email sender without AUTH errors with  javax.mail.MessagingException: Invalid Addresses
TLS SMTP AUTH sender works fine

**How can one reproduce the bug?**
1. Configure sender to use the local Postfix server with default config (not configured for SMTP-AUTH)
2. Configure email destination using the sender above
3. Try sending alert to the destination configured above
4. See error: javax.mail.MessagingException: Invalid Addresses

**What is the expected behavior?**
The email should be sent successfully

**What is your host/environment?**
 - OS: OpenSearch docker container on Ubuntu 18.04
 - Version: 1.3.2
 - Alerting plugin version: 1.3.2.0

An attempt to configure the sender without SMTP-AUTH (local Postfix or direct send to MS Office 365 cloud) fails with "javax.mail.MessagingException: Invalid Addresses":

`[2022-05-24T15:49:15,538][DEBUG][o.o.a.r.RestGetDestinationsAction] [opensearch01] GET /_plugins/_alerting/destinations
[2022-05-24T15:49:15,538][DEBUG][o.o.a.t.SecureTransportAction] [opensearch01] User and roles string from thread context: andrija.pantovic@phoenix-systems.ch|admin|own_index,all_access|admin
[2022-05-24T15:49:15,538][DEBUG][o.o.a.t.SecureTransportAction] [opensearch01] Is filterByEnabled: false ; Is admin user: true
[2022-05-24T15:49:23,079][DEBUG][o.o.a.r.RestExecuteMonitorAction] [opensearch01] POST /_plugins/_alerting/monitors/_execute
[2022-05-24T15:49:23,080][DEBUG][o.o.a.t.TransportGetMonitorAction] [opensearch01] User and roles string from thread context: andrija.pantovic@phoenix-systems.ch|admin|own_index,all_access|admin
[2022-05-24T15:49:23,080][DEBUG][o.o.a.MonitorRunner      ] [opensearch01] Running monitor: kore_hsm_syslog_test with roles: [own_index, all_access] Thread: DefaultDispatcher-worker-8
[2022-05-24T15:49:24,090][ERROR][o.o.a.d.f.EmailDestinationFactory] [opensearch01] Exception publishing Message: DestinationType: EMAIL, DestinationName: my_test, Host: phoenixsystems-ch01i.mail.protection.outlook.com, Port: 25, Message: Monitor kore_hsm_syslog_test just entered alert status. Please investigate the issue.
  - Total hits: 
  - Trigger: severe_events
  - Severity: 1
  - Period start: 2022-05-24T15:48:23.079Z
  - Period end: 2022-05-24T15:49:23.079Z

javax.mail.MessagingException: Invalid Addresses
        at org.opensearch.alerting.destination.client.DestinationEmailClient.execute(DestinationEmailClient.java:79) ~[alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.destination.factory.EmailDestinationFactory.publish(EmailDestinationFactory.java:31) [alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.destination.factory.EmailDestinationFactory.publish(EmailDestinationFactory.java:18) [alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.destination.Notification.lambda$publish$0(Notification.java:35) [alerting-notification-1.3.2.0.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) [?:?]
        at org.opensearch.alerting.destination.Notification.publish(Notification.java:33) [alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.model.destination.Destination.publish(Destination.kt:298) [opensearch-alerting-1.3.2.0.jar:1.3.2.0]
        at org.opensearch.alerting.MonitorRunner$runAction$2.invokeSuspend(MonitorRunner.kt:659) [opensearch-alerting-1.3.2.0.jar:1.3.2.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
[2022-05-24T15:49:24,091][INFO ][o.o.a.m.MonitorRunResult ] [opensearch01] Internal error: javax.mail.MessagingException: Invalid Addresses. See the opensearch.log for details
java.lang.IllegalStateException: javax.mail.MessagingException: Invalid Addresses
        at org.opensearch.alerting.destination.factory.EmailDestinationFactory.publish(EmailDestinationFactory.java:36) ~[alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.destination.factory.EmailDestinationFactory.publish(EmailDestinationFactory.java:18) ~[alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.destination.Notification.lambda$publish$0(Notification.java:35) ~[alerting-notification-1.3.2.0.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.opensearch.alerting.destination.Notification.publish(Notification.java:33) ~[alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.model.destination.Destination.publish(Destination.kt:298) ~[opensearch-alerting-1.3.2.0.jar:1.3.2.0]
        at org.opensearch.alerting.MonitorRunner$runAction$2.invokeSuspend(MonitorRunner.kt:659) ~[opensearch-alerting-1.3.2.0.jar:1.3.2.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
Caused by: javax.mail.MessagingException: Invalid Addresses
        at org.opensearch.alerting.destination.client.DestinationEmailClient.execute(DestinationEmailClient.java:79) ~[alerting-notification-1.3.2.0.jar:?]
        at org.opensearch.alerting.destination.factory.EmailDestinationFactory.publish(EmailDestinationFactory.java:31) ~[alerting-notification-1.3.2.0.jar:?]
        ... 11 more
`

When SMTP AUTH client configured (for example MS Office 365 smtp.office365.com:587 with TLS and credentials set in the keystore) the setup works fine:

`2022-05-24T15:59:05,415][DEBUG][o.o.a.r.RestExecuteMonitorAction] [opensearch02] POST /_plugins/_alerting/monitors/_execute
[2022-05-24T15:59:05,416][DEBUG][o.o.a.t.TransportGetMonitorAction] [opensearch02] User and roles string from thread context: andrija.pantovic@phoenix-systems.ch|admin|own_index,all_access|admin
[2022-05-24T15:59:05,417][DEBUG][o.o.a.MonitorRunner      ] [opensearch02] Running monitor: kore_hsm_syslog_test with roles: [own_index, all_access] Thread: DefaultDispatcher-worker-1
[2022-05-24T15:59:06,923][INFO ][o.o.a.m.d.Destination    ] [opensearch02] Message published for action name: my_test, messageid: Sent, statuscode: 0`

**Comment by praveensameneni** [comment]
Looking into the issue.

**Comment by maumrsms** [comment]
Presented same issue too and got some additional errors using different email addresses:
Hotmail account directly → Errors: `javax.mail.MessagingException: Can't send command to SMTP host`
Hotmail account through postfix (no encrytion) → Errors: `javax.mail.MessagingException: Invalid Addresses`
Paid hosting email using SSL → Errors: `javax.mail.MessagingException: Can't send command to SMTP host`
Paid hosting email using TLS → Errors: `javax.mail.MessagingException: Could not connect to SMTP host: <SMTP_SERVER_HERE>, port: 465, response: -1`
Paid hosting email no ecryption → `Errors: javax.mail.MessagingException: 550 Access denied - Invalid HELO name (See RFC2821 4.1.1.1)`

I have confirmed that SMTP works in all my used email addresses and also having set credentials for Alerting module as explained [here](https://opensearch.org/docs/latest/monitoring-plugins/alerting/monitors/#authenticate-sender-account). Still nothing is sent.

**Comment by maumrsms** [comment]
Hello @praveensameneni any news about this?

**Comment by raj-chak** [comment]
Hi I was able to replicate this issue on both the docker Version: 1.3.2 image and docker Version: 2.2.0 image.
The fix is as follows:
Change the config in /etc/postfix/main.cf to add the following ( Please append the IP addresses if others exist ) 
inet_interfaces = 172.17.0.1
mynetworks = 172.17.0.2
# In the above case 172.17.0.1 is the bridge  gateway and 172.17.0.2 is the IPAddress of the container
# that you can obtain by docker inspect container ...
# Please restart the postfix server
Also please make sure that you put 172.17.0.1 as the SMTP sender host using the opensearch dashboard GUI

**Comment by maumrsms** [comment]
Thank you @raj-chak! the provided configuration works correctly with my Postfix server.
Still, it would be interesting to get a fix or workaround to use with an email address directly configured into Opensearch (without a Postfix server)
