### ISSUE TITLE
Root mapping definition has unsupported parameters when creating monitor

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#48]
<a href="https://github.com/dennyx"><img src="https://avatars.githubusercontent.com/u/8176446?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dennyx](https://github.com/dennyx)**
_Monday Sep 16, 2019 at 08:51 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/103_

----

Hi,
I have a fresh installed cluster with Opendistro version: **1.1.0**
**Issue**:
When trying to create monitor in kibana alert panel, while could not found any data in UI, and check elasticsearch logs, get below errors.
Expected could successfully get data in create monitor page.
Appreciate if any kindly help, thanks.
`[2019-09-06T09:00:39,700][ERROR][c.a.o.a.MonitorRunner    ] [elasticcluster] Error loading alerts for monitor: _na_
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_doc : {}]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:394) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:323) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:476) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.1.1.jar:7.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [_doc : {}]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:152) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:140) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:392) ~[elasticsearch-7.1.1.jar:7.1.1]
        ... 15 more`
![image](https://user-images.githubusercontent.com/8176446/64416973-c5ae0c80-d0ca-11e9-9c41-78f8dd43a4f7.png)

**Comment by aditjind** [comment]
<a href="https://github.com/lucaswin-amzn"><img src="https://avatars.githubusercontent.com/u/46609415?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lucaswin-amzn](https://github.com/lucaswin-amzn)**
_Tuesday Oct 29, 2019 at 16:59 GMT_

----

Hi @dennyx,

Could you please share your alerting config mappings?

Please provide the output to the following commands:

1.
```
curl -X GET '<endpoint>/.opendistro-alerting-config/_mapping?pretty'
```

2.
```
curl -X GET '<endpoint>/.opendistro-alerting-alerts/_mapping?pretty'
```

**Comment by aditjind** [comment]
<a href="https://github.com/dennyx"><img src="https://avatars.githubusercontent.com/u/8176446?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dennyx](https://github.com/dennyx)**
_Thursday Oct 31, 2019 at 02:17 GMT_

----

hi @lucaswin-amzn ,
Thanks for the kindly feedback.
**/.opendistro-alerting-config/_mapping?pretty** output as below:

[opendistro-alerting-config.output.txt](https://github.com/opendistro-for-elasticsearch/alerting/files/3791851/opendistro-alerting-config.output.txt)

**.opendistro-alerting-alerts/_mapping?pretty** output as below:
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [.opendistro-alerting-alerts]",
        "resource.type" : "index_or_alias",
        "resource.id" : ".opendistro-alerting-alerts",
        "index_uuid" : "_na_",
        "index" : ".opendistro-alerting-alerts"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [.opendistro-alerting-alerts]",
    "resource.type" : "index_or_alias",
    "resource.id" : ".opendistro-alerting-alerts",
    "index_uuid" : "_na_",
    "index" : ".opendistro-alerting-alerts"
  },
  "status" : 404
}
```

Appreciate for the kindly help~

**Comment by aditjind** [comment]
<a href="https://github.com/mmiller1"><img src="https://avatars.githubusercontent.com/u/25506816?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmiller1](https://github.com/mmiller1)**
_Thursday Dec 05, 2019 at 18:54 GMT_

----

I'm also seeing this issue on a new 7.2 cluster.

**Comment by aditjind** [comment]
<a href="https://github.com/mmiller1"><img src="https://avatars.githubusercontent.com/u/25506816?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmiller1](https://github.com/mmiller1)**
_Thursday Dec 05, 2019 at 20:10 GMT_

----

Odd. I redeployed the cluster (using helm) with the exact same configuration and it is now working for me.

**Comment by aditjind** [comment]
<a href="https://github.com/vikram251186"><img src="https://avatars.githubusercontent.com/u/22957804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vikram251186](https://github.com/vikram251186)**
_Thursday Dec 12, 2019 at 10:46 GMT_

----

Hi,

I also have this error on my Elasticsearch node 7.2. Unable to resolve it.
Kindly help please.
See my .opendistro-alerting-config mapping attached.
[opendistro-alerting-config_mapping.txt](https://github.com/opendistro-for-elasticsearch/alerting/files/3955317/opendistro-alerting-config_mapping.txt)

**Comment by aditjind** [comment]
<a href="https://github.com/dennyx"><img src="https://avatars.githubusercontent.com/u/8176446?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dennyx](https://github.com/dennyx)**
_Thursday Feb 06, 2020 at 09:59 GMT_

----

Temp work around for this issue, tested passed in my instance
A. manual delete **.opendistro-alerting-config** index.
B. run docker instance for elasticsearch&kibana locally, and get all alerting related indexes.
C. Create all alerting related indexes, keep the same with above 
1. .opendistro-alerting-alert-history-2020.02.06-1 (the day you config for this)
2. .opendistro-alerting-alerts
3. .opendistro-alerting-config
