### ISSUE TITLE
[Bug] Alerting failed on publishzip task on macOS

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/alerting#516]
https://build.ci.opensearch.org/job/distribution-build-opensearch/5902/execution/node/276/log/

```
+ ./gradlew publishPluginZipPublicationToZipStagingRepository -Dopensearch.version=2.2.0-SNAPSHOT -Dbuild.snapshot=true -Dbuild.version_qualifier=
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 12.4 (x86_64)
  JDK Version           : 17 (Eclipse Temurin JDK)
  JAVA_HOME             : /private/var/jenkins/tools/hudson.model.JDK/openjdk-17
  Random Testing Seed   : 993604F0DFB01868
  In FIPS 140 mode      : false
=======================================

> Task :ktlint
/private/var/folders/2g/jjj_bgln5qn8c6t1szz_fmmc0000gn/T/tmpwp0wt1qz/alerting/alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt:40:1: Exceeded max line length (140) (cannot be auto-corrected) (max-line-length)
/private/var/folders/2g/jjj_bgln5qn8c6t1szz_fmmc0000gn/T/tmpwp0wt1qz/alerting/alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt:42:1: Exceeded max line length (140) (cannot be auto-corrected) (max-line-length)
/private/var/folders/2g/jjj_bgln5qn8c6t1szz_fmmc0000gn/T/tmpwp0wt1qz/alerting/alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt:63:1: Exceeded max line length (140) (cannot be auto-corrected) (max-line-length)
/private/var/folders/2g/jjj_bgln5qn8c6t1szz_fmmc0000gn/T/tmpwp0wt1qz/alerting/alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt:65:1: Exceeded max line length (140) (cannot be auto-corrected) (max-line-length)

> Task :ktlint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ktlint'.
> Process 'command '/private/var/jenkins/tools/hudson.model.JDK/openjdk-17/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
1 actionable task: 1 executed
2022-08-09 00:57:02 ERROR    Error building alerting, retry with: ./build.sh manifests/2.2.0/opensearch-2.2.0.yml --component alerting --snapshot
Traceback (most recent call last):
  File "./src/run_build.py", line 81, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 68, in main
    builder.build(build_recorder)
  File "/private/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/builder_from_source.py", line 55, in build
    self.git_repo.execute(build_command)
  File "/private/var/jenkins/workspace/distribution-build-opensearch/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /private/var/folders/2g/jjj_bgln5qn8c6t1szz_fmmc0000gn/T/tmpwp0wt1qz/alerting/scripts/build.sh -v 2.2.0 -p darwin -a x64 -s true -o builds' returned non-zero exit status 1.
```

**Comment by peterzhuamazon** [comment]
Hi @prudhvigodithi please work with @opensearch-project/alerting-plugin owners on this.
Thanks.
