### ISSUE TITLE
[BUG] query/bucket level monitor re-write query causing Script Circuit Breaker at 1000 monitor scale

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/alerting#915]
**What is the bug?**
https://github.com/opensearch-project/alerting/blob/1.3/alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt#L68-L75
**The code mentioned in above link is creating a script based search source in every single run of query level and bucket level monitor. This is not scalable for 1000 query/bucket level monitors running every minute requiring 1000 script compilations on top of painless, mustache trigger evaluations required.**
```
val rewrittenQuery = AggregationQueryRewriter.rewriteQuery(deepCopyQuery(input.query), prevResult, monitor.triggers)
                        val searchSource = scriptService.compile(
                            Script(
                                ScriptType.INLINE, Script.DEFAULT_TEMPLATE_LANG,
                                rewrittenQuery.toString(), searchParams
                            ),
                            TemplateScript.CONTEXT
                        )
                            .newInstance(searchParams)
                            .execute()
```

Issue
It's not just the Customer's painless scripts in the trigger or the search query itself that's causing the issue. it's the logic in Query/Bucket level monitor where query is re-written and then passed as an INLINE SCRIPT being compiled in mustache lang
```
[2023-05-11T23:00:00,172][INFO ][o.o.a.InputService       ] [ed6f04d264c4ea5d66537f208ba396e1] Error collecting inputs for monitor: ZHqBRocB6f54-Rz3boAe
GeneralScriptException[Failed to compile inline script [{"size":0,"query":{"bool":{"must":[{"term":{"metricname.keyword":{"value":"Health","boost":1.0}}},{"terms":{"dim_instance.keyword":["account-85-kconn-instance-2"],"boost":1.0}}],"filter":[{"range":{"timestamp":{"from":"now-5m","to":"now","include_lower":true,"include_upper":true,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"aggregations":{"instances":{"terms":{"field":"dbsdfbsfd.keyword","size":1000,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]},"aggregations":{"dbfsdfb":{"avg":{"field":"value"}},"sdfbsdfbsdfb":{"bucket_selector":{"buckets_path":{"bsdfbsdnstndf":"bsdfbsdnstndf"},"script":{"source":"params.bsdfbsdnstndf<params['compareValue']","lang":"painless","params":{"dberge":1}},"gap_policy":"skip"}}}},"rhaerhbaer":{"terms":{"field":"dim_instance.keyword","size":1000,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]},"aggregations":{"statisticValue":{"avg":{"field":"value"}},"filter_instances_with_value_alert_threshold":{"bucket_selector":{"buckets_path":{"bsdfbsdnstndf":"bsdfbsdnstndf"},"script":{"source":"!(params.bsdfbsdnstndf<params['dberge'])","lang":"painless","params":{"dberge":1}},"gap_policy":"skip"}}}}}}] using lang [mustache]]; nested: CircuitBreakingException[[script] Too many dynamic script compilations within, max: [300/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting];
        at org.opensearch.script.ScriptCache.compile(ScriptCache.java:134)
        at org.opensearch.script.ScriptService.compile(ScriptService.java:491)
        at org.opensearch.alerting.InputService.collectInputResults(InputService.kt:69)
        at org.opensearch.alerting.InputService.collectInputResults$default(InputService.kt:50)
        at org.opensearch.alerting.MonitorRunner$runQueryLevelMonitor$2.invokeSuspend(MonitorRunner.kt:283)
        at org.opensearch.alerting.MonitorRunner$runQueryLevelMonitor$2.invoke(MonitorRunner.kt)
        at org.opensearch.alerting.elasticapi.ElasticExtensionsKt$withClosableContext$2.invokeSuspend(ElasticExtensions.kt:210)
        at org.opensearch.alerting.elasticapi.ElasticExtensionsKt$withClosableContext$2.invoke(ElasticExtensions.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:146)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at org.opensearch.alerting.elasticapi.ElasticExtensionsKt.withClosableContext(ElasticExtensions.kt:210)
        at org.opensearch.alerting.MonitorRunner.runQueryLevelMonitor(MonitorRunner.kt:282)
        at org.opensearch.alerting.MonitorRunner$runQueryLevelMonitor$1.invokeSuspend(MonitorRunner.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: CircuitBreakingException[[script] Too many dynamic script compilations within, max: [300/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting]
        at org.opensearch.script.ScriptCache.checkCompilationLimit(ScriptCache.java:192)
        at org.opensearch.script.ScriptCache.lambda$compile$0(ScriptCache.java:122)
        at org.opensearch.common.cache.Cache.computeIfAbsent(Cache.java:447)
        at org.opensearch.script.ScriptCache.compile(ScriptCache.java:107)
        ... 18 more
```
**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by eirsep** [comment]
Tagging @rishabhmaurya @qreshi @getsaurabh02 @lezzago to brainstorn 
**1. if we need query re-writing for query level monitors also or can we limit to bucket level monitors
2. how to work with script cache/resource limits
3. benchmarking each monitor**

**Comment by qreshi** [comment]
It's worth checking how resource intensive the script compile footprint is when 1000 monitors are running. If the average cluster can handle it, we can recommend a larger `script.max_compilations_rate` for these higher scale workloads.

Ideally, we could try to use scripts with parameters and cache the compiled script in memory. Then if the query is every edited, we invalidate the cache and refresh it. Then we shouldn't have to compile for this on each run (in theory). However, since the rewritten query needs the previous results to create a `SearchSourceBuilder` which is mutating on every execution, we need to see if it's even possible to parameterize this. @rishabhmaurya @getsaurabh02 @lezzago Thoughts?

**Comment by petardz** [comment]
[Mustache script](https://github.com/opensearch-project/alerting/blob/1.3/alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt#L68-L75) used by queryLevel and bucketLevel monitors seems to be parametrised and cached by core's ScriptEngine impl: [link](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/script/ScriptService.java#L496)

**Comment by lezzago** [comment]
That approach seems to be good. Does this mean that `my_script_context` would be alerting since we would want to only control it at the plugin level?
